filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/main-app/*.log
      - /logs/tcp-simulator/*.log
      - /logs/rest-simulator/*.log
      - /logs/kafka-consumer/*.log
      - /logs/kafka-consumer-opensearch/*.log
    fields:
      application: finansal_rates
    fields_under_root: true
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'
      negate: true
      match: after

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

setup.template.name: "finansal-rates-logs"
setup.template.pattern: "finansal-rates-logs-*"
setup.ilm.enabled: false
setup.template.enabled: true
output.elasticsearch:

  hosts: ["opensearch:9200"]
  protocol: "http"
  username: ""
  password: ""
  index: "finansal-rates-logs-%{+yyyy.MM.dd}"
  setup.template.enabled: false
  setup.ilm.enabled: false

logging.level: info