version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - finansal_network
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "finansal.rates:1:1"
    depends_on:
      - zookeeper
    networks:
      - finansal_network
    volumes:
      - kafka-data:/var/lib/kafka/data

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - finansal_network
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finansal_rates
    ports:
      - "5432:5432"
    networks:
      - finansal_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:2.4.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
    networks:
      - finansal_network
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  tcp-simulator:
    build:
      context: ./demo
    container_name: tcp-simulator
    ports:
      - "8081:8081"
    networks:
      - finansal_network
    depends_on:
      - kafka

  rest-simulator:
    build:
      context: ./platform-simulator-rest
    container_name: rest-simulator
    ports:
      - "8080:8080"
    networks:
      - finansal_network
    depends_on:
      - kafka

  main-app:
    build:
      context: ./main-app
    container_name: main-app
    ports:
      - "8090:8090"
    networks:
      - finansal_network
    environment:
      - TCP_PLATFORM_HOST=tcp-simulator
      - TCP_PLATFORM_PORT=8081
      - REST_PLATFORM_HOST=rest-simulator
      - REST_PLATFORM_PORT=8080
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - tcp-simulator
      - rest-simulator
      - redis
      - kafka
      - postgres
      - opensearch # main-app'in OpenSearch'e de ihtiyacı olabilir

  kafka-consumer:
    build:
      context: ./Kafka-Consumer
    container_name: kafka-consumer
    networks:
      - finansal_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/finansal_rates
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_RATES=finansal.rates
    depends_on:
      - kafka
      - postgres
      - main-app

  kafka-consumer-opensearch:
    build:
      context: ./kafka-consumer-opensearch
    container_name: kafka-consumer-opensearch
    networks:
      - finansal_network
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_RATES=finansal.rates
      - OPENSEARCH_URL=http://opensearch:9200
    depends_on:
      - kafka
      - opensearch
      - main-app

networks:
  finansal_network:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data:
  redis-data:
  postgres-data:
  opensearch-data: