version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - finansal_network
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    healthcheck:
      test: [ "CMD-SHELL", "echo 'ruok' | nc localhost 2181 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "finansal.rates:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - finansal_network
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:29092 --list || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: on-failure

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - finansal_network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finansal_rates
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - finansal_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.4.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
    networks:
      - finansal_network
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  tcp-simulator:
    build:
      context: ./demo
    container_name: tcp-simulator
    ports:
      - "8081:8081"
    networks:
      - finansal_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 5s
      retries: 3

  rest-simulator:
    build:
      context: ./platform-simulator-rest
    container_name: rest-simulator
    ports:
      - "8080:8080"
    networks:
      - finansal_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/rates"]
      interval: 10s
      timeout: 5s
      retries: 3

  main-app:
    build:
      context: ./main-app
    container_name: main-app
    ports:
      - "8090:8090"
    environment:
      - TCP_PLATFORM_HOST=tcp-simulator
      - TCP_PLATFORM_PORT=8081
      - REST_PLATFORM_HOST=rest-simulator
      - REST_PLATFORM_PORT=8080
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC_RATES=finansal.rates
      - SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES=true
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
      - CACHE_TYPE=memory
      - JAVA_OPTS=-Xmx512m
    networks:
      - finansal_network
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      tcp-simulator:
        condition: service_started
      rest-simulator:
        condition: service_started
    restart: on-failure

  kafka-consumer:
    build:
      context: ./Kafka-Consumer
    container_name: kafka-consumer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/finansal_rates
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC_RATES=finansal.rates
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES=true
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
      - JAVA_OPTS=-Xmx512m
    networks:
      - finansal_network
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      main-app:
        condition: service_started
    restart: on-failure

  kafka-consumer-opensearch:
    build:
      context: ./kafka-consumer-opensearch
    container_name: kafka-consumer-opensearch
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC_RATES=finansal.rates
      - OPENSEARCH_URL=http://opensearch:9200
      - SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES=true
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
      - JAVA_OPTS=-Xmx512m
      - SPRING_RETRY_ENABLED=true
      - SPRING_RETRY_MAX_ATTEMPTS=10
      - SPRING_RETRY_INITIAL_INTERVAL=5000
    networks:
      - finansal_network
    depends_on:
      kafka:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      main-app:
        condition: service_started
    restart: on-failure

networks:
  finansal_network:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data:
  redis-data:
  postgres-data:
  opensearch-data: